<?php
/**
 * @file
 * Code for the Landing pages feature.
 */

include_once 'landing_pages.features.inc';

function landing_pages_node_view($node, $view_mode, $langcode) {
  // embed javascript on landing page display
  if ($node->type == 'full_page') {
    drupal_add_css(drupal_get_path('module', 'landing_pages') . '/landing_pages.css');
    drupal_add_js(drupal_get_path('module', 'landing_pages') . '/landing_pages.js');
  }
}

/**
 * Implements hook_block_info().
 */
function landing_pages_block_info() {
  $blocks = array(
    'landing_pages_element1' => array(
      'title' => '<none>',
      'info' => t('Custom block for front page'),
    ),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function landing_pages_block_configure($delta='') {
  global $language;

  $form = array();

  switch($delta) {

    case 'landing_pages_element1':
      // Text field form element
      $form['text_body'] = array(
        '#type' => 'text_format',
        '#title' => t("Custom text"),
        '#default_value' => $text = variable_get('landing_pages_element1_'.$language->language, variable_get('landing_pages_element1_en', 'Learn more')),
        //'#default_value' => $text = variable_get('landing_pages_element1', 'Learn more about Jeeves ERP'),
        '#wysiwyg' => true,
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function landing_pages_block_save($delta = '', $edit = array()) {
  global $language;

  switch($delta) {

    case 'landing_pages_element1' :
      // Saving the WYSIWYG text
      variable_set('landing_pages_element1_'.$language->language, $edit['text_body']['value']);
      //variable_set('landing_pages_element1', $edit['text_body']['value']);
      break;

  }
}

/**
 * Implements hook_block_view().
 */
function landing_pages_block_view($delta='') {
  $block = array();

  switch($delta) {

    case 'landing_pages_element1' :
      $block['content'] = _landing_pages_element1_view();
      break;

  }

  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function _landing_pages_element1_view() {

  global $language;

  $block = array();

  // Capture WYSIWYG text from the variable
  $label = variable_get('landing_pages_element1_'.$language->language, variable_get('landing_pages_element1_en', 'Learn more'));
  // $link = '<p><a href="#more-info" onClick="scroll_animate(\'more-info\');return false;" id="customanchor1">'.$label.'</a></p><script>function scroll_animate(elem) {jQuery(\'body,html\').stop(true,true).animate({
  //     \'scrollTop\':   jQuery(\'#\'+elem).offset().top - 60
  //   }, 1000); return false;}</script>';
  $link = '<p><a href="#more-info" id="customanchor1">'.$label.'</a></p>';

  // Block output in HTML with div wrapper
  $block = array(
    'custom-text' => array(
      '#prefix' => '<div class="landing-pages-element1 full-pages-element1"><div class="content">',
      '#suffix' => '</div></div>',
      '#type' => 'markup',
      '#markup' => $link,
    ),
  );

  return $block;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function landing_pages_form_node_form_alter(&$form, $form_state, $form_id) {

  // Switch full view mode.
  if ($form['#node']->type == 'landing_page') {
    if (isset($form['ds_extras']) && isset($form['ds_extras']['ds_switch'])) {
      $node = $form['#node'];
      $form['ds_extras']['ds_switch']['#default_value'] = isset($node->ds_switch) ? $node->ds_switch : 'ds_with_sidebar';

    }
  }
}


/**
 * Implements hook_views_pre_execute()
 *
 *  Changes the view query to order by the delta,
 *  because views does not know how to handle this.
 *
 */
function landing_pages_views_pre_execute(&$view) {
  if ($view->name == 'landing_page_slides') {
    $query = $view->build_info['query'];
    $query->orderBy('field_data_field_slide.delta', 'ASC');
    $query->distinct();
    $view->build_info['query'] = $query;
  }
}


