<?php
/**
 * @file
 * Code for the Landing pages feature.
 */

include_once 'landing_pages.features.inc';


/**
 * Alter the menu tree and its configuration before the tree is rendered.
 *
 * @param $tree
 *   An array containing the unrendered menu tree.
 * @param $config
 *   An array containing the configuration of the tree.
 */
function landing_pages_menu_block_tree_alter(&$tree, &$config) {

  // dpm($tree);
  // dpm($config);
}
